name: photo_sync
description: A new Flutter project.
publish_to: 'none'

version: 0.7.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^4.0.0 # HTTP/HTTPS requests
  pretty_dio_logger: ^1.2.0-beta-1 # Logs the http/https requests
  rxdart: ^0.27.0 # State management
  storage_wrapper: ^2.0.0 # Settings/info storage save
  cached_network_image: ^3.0.0 # Network image renderer
  flutter_feather_icons: ^2.0.0+1 # Icons
  flutter_svg: ^0.23.0+1 # Svg render
  google_nav_bar: ^5.0.5 # Navigation bar
  photo_manager: ^1.2.1 # Returns the media from the local disk
  photo_view: ^0.13.0 # Zoomable image
  filesize: ^2.0.1 # Handles the bytes conversion
  path_provider: ^2.0.2 # Temporary, needs to find a better solution to get the save file path
  flutter_cache_manager: ^3.1.2 # Cache manager for the objects
  easy_localization: ^3.0.0 # Localization
  geocoding: ^2.0.1
  sqflite: ^2.0.0+4 # Database
  json_annotation: ^4.3.0
  rive: ^0.7.33 # Animations

dev_dependencies:
  flutter_lints: ^1.0.4
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/on_boarding/
    - assets/translations/
    - assets/animations/